/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _background_game_button_smasher_h_
#define _background_game_button_smasher_h_
//---------------------------------------------------------------------------------
extern const unsigned char background_game_button_smasher[];
extern const int background_game_button_smasher_size;
//---------------------------------------------------------------------------------
#endif //_background_game_button_smasher_h_
//---------------------------------------------------------------------------------
