/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _button_play_selected_h_
#define _button_play_selected_h_
//---------------------------------------------------------------------------------
extern const unsigned char button_play_selected[];
extern const int button_play_selected_size;
//---------------------------------------------------------------------------------
#endif //_button_play_selected_h_
//---------------------------------------------------------------------------------
