/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _button_about_h_
#define _button_about_h_
//---------------------------------------------------------------------------------
extern const unsigned char button_about[];
extern const int button_about_size;
//---------------------------------------------------------------------------------
#endif //_button_about_h_
//---------------------------------------------------------------------------------
