/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _button_resume_h_
#define _button_resume_h_
//---------------------------------------------------------------------------------
extern const unsigned char button_resume[];
extern const int button_resume_size;
//---------------------------------------------------------------------------------
#endif //_button_resume_h_
//---------------------------------------------------------------------------------
