/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _button_back_selected_h_
#define _button_back_selected_h_
//---------------------------------------------------------------------------------
extern const unsigned char button_back_selected[];
extern const int button_back_selected_size;
//---------------------------------------------------------------------------------
#endif //_button_back_selected_h_
//---------------------------------------------------------------------------------
