/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _button_options_h_
#define _button_options_h_
//---------------------------------------------------------------------------------
extern const unsigned char button_options[];
extern const int button_options_size;
//---------------------------------------------------------------------------------
#endif //_button_options_h_
//---------------------------------------------------------------------------------
