/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _button_quit_selected_h_
#define _button_quit_selected_h_
//---------------------------------------------------------------------------------
extern const unsigned char button_quit_selected[];
extern const int button_quit_selected_size;
//---------------------------------------------------------------------------------
#endif //_button_quit_selected_h_
//---------------------------------------------------------------------------------
