/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _wii_remote_warning_h_
#define _wii_remote_warning_h_
//---------------------------------------------------------------------------------
extern const unsigned char wii_remote_warning[];
extern const int wii_remote_warning_size;
//---------------------------------------------------------------------------------
#endif //_wii_remote_warning_h_
//---------------------------------------------------------------------------------
