/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _icon_game_button_smasher_h_
#define _icon_game_button_smasher_h_
//---------------------------------------------------------------------------------
extern const unsigned char icon_game_button_smasher[];
extern const int icon_game_button_smasher_size;
//---------------------------------------------------------------------------------
#endif //_icon_game_button_smasher_h_
//---------------------------------------------------------------------------------
