/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _icon_template_h_
#define _icon_template_h_
//---------------------------------------------------------------------------------
extern const unsigned char icon_template[];
extern const int icon_template_size;
//---------------------------------------------------------------------------------
#endif //_icon_template_h_
//---------------------------------------------------------------------------------
